// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/transport/transportpb/frame.proto

package transportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrameType identifies the logical stream a frame belongs to. The value is
// carried in the fixed binary header's 1-byte `type` field (see frame.go).
type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	FrameType_FRAME_TYPE_AUDIO       FrameType = 1 // payload = raw PCM bytes (NOT protobuf)
	FrameType_FRAME_TYPE_TEXT        FrameType = 2 // payload = TextPayload
	FrameType_FRAME_TYPE_CONTROL     FrameType = 3 // payload = ControlPayload
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "FRAME_TYPE_AUDIO",
		2: "FRAME_TYPE_TEXT",
		3: "FRAME_TYPE_CONTROL",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_AUDIO":       1,
		"FRAME_TYPE_TEXT":        2,
		"FRAME_TYPE_CONTROL":     3,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_transportpb_frame_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_internal_transport_transportpb_frame_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_transportpb_frame_proto_rawDescGZIP(), []int{0}
}

// TextSource tells the client which conversational lane a TEXT frame
// belongs to, so transcripts and agent subtitles render separately.
type TextSource int32

const (
	TextSource_TEXT_SOURCE_UNSPECIFIED TextSource = 0
	TextSource_TEXT_SOURCE_TRANSCRIPT  TextSource = 1 // ASR result: what the user said
	TextSource_TEXT_SOURCE_TOKEN       TextSource = 2 // LLM token: what the agent is saying
)

// Enum value maps for TextSource.
var (
	TextSource_name = map[int32]string{
		0: "TEXT_SOURCE_UNSPECIFIED",
		1: "TEXT_SOURCE_TRANSCRIPT",
		2: "TEXT_SOURCE_TOKEN",
	}
	TextSource_value = map[string]int32{
		"TEXT_SOURCE_UNSPECIFIED": 0,
		"TEXT_SOURCE_TRANSCRIPT":  1,
		"TEXT_SOURCE_TOKEN":       2,
	}
)

func (x TextSource) Enum() *TextSource {
	p := new(TextSource)
	*p = x
	return p
}

func (x TextSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextSource) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_transportpb_frame_proto_enumTypes[1].Descriptor()
}

func (TextSource) Type() protoreflect.EnumType {
	return &file_internal_transport_transportpb_frame_proto_enumTypes[1]
}

func (x TextSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextSource.Descriptor instead.
func (TextSource) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_transportpb_frame_proto_rawDescGZIP(), []int{1}
}

// ControlKind enumerates control-plane signals.
type ControlKind int32

const (
	ControlKind_CONTROL_KIND_UNSPECIFIED ControlKind = 0
	ControlKind_CONTROL_KIND_START       ControlKind = 1
	ControlKind_CONTROL_KIND_STOP        ControlKind = 2
	ControlKind_CONTROL_KIND_BARGE_IN    ControlKind = 3
	ControlKind_CONTROL_KIND_ERROR       ControlKind = 4
)

// Enum value maps for ControlKind.
var (
	ControlKind_name = map[int32]string{
		0: "CONTROL_KIND_UNSPECIFIED",
		1: "CONTROL_KIND_START",
		2: "CONTROL_KIND_STOP",
		3: "CONTROL_KIND_BARGE_IN",
		4: "CONTROL_KIND_ERROR",
	}
	ControlKind_value = map[string]int32{
		"CONTROL_KIND_UNSPECIFIED": 0,
		"CONTROL_KIND_START":       1,
		"CONTROL_KIND_STOP":        2,
		"CONTROL_KIND_BARGE_IN":    3,
		"CONTROL_KIND_ERROR":       4,
	}
)

func (x ControlKind) Enum() *ControlKind {
	p := new(ControlKind)
	*p = x
	return p
}

func (x ControlKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_transportpb_frame_proto_enumTypes[2].Descriptor()
}

func (ControlKind) Type() protoreflect.EnumType {
	return &file_internal_transport_transportpb_frame_proto_enumTypes[2]
}

func (x ControlKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlKind.Descriptor instead.
func (ControlKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_transportpb_frame_proto_rawDescGZIP(), []int{2}
}

// TextPayload carries an incremental or final transcript / token.
type TextPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Final         bool                   `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"` // true = final (e.g. ASR final / utterance end)
	Source        TextSource             `protobuf:"varint,3,opt,name=source,proto3,enum=voicestream.transport.v1.TextSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPayload) Reset() {
	*x = TextPayload{}
	mi := &file_internal_transport_transportpb_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPayload) ProtoMessage() {}

func (x *TextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_transportpb_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPayload.ProtoReflect.Descriptor instead.
func (*TextPayload) Descriptor() ([]byte, []int) {
	return file_internal_transport_transportpb_frame_proto_rawDescGZIP(), []int{0}
}

func (x *TextPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextPayload) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *TextPayload) GetSource() TextSource {
	if x != nil {
		return x.Source
	}
	return TextSource_TEXT_SOURCE_UNSPECIFIED
}

// ControlPayload carries a control-plane signal.
//
// START doubles as the session handshake (M8). Client -> server: session_id
// empty for a new session, or a previous id with a claimed epoch strictly
// greater than the last known one to resume; last_seq is the highest downlink
// seq the client received. Server -> client (the ack): the authoritative
// session_id/epoch, and last_seq = the highest uplink seq the server has
// delivered (the client may skip replaying anything at or below it).
type ControlPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ControlKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=voicestream.transport.v1.ControlKind" json:"kind,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // optional human-readable detail (e.g. error message)
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPayload) Reset() {
	*x = ControlPayload{}
	mi := &file_internal_transport_transportpb_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPayload) ProtoMessage() {}

func (x *ControlPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_transportpb_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPayload.ProtoReflect.Descriptor instead.
func (*ControlPayload) Descriptor() ([]byte, []int) {
	return file_internal_transport_transportpb_frame_proto_rawDescGZIP(), []int{1}
}

func (x *ControlPayload) GetKind() ControlKind {
	if x != nil {
		return x.Kind
	}
	return ControlKind_CONTROL_KIND_UNSPECIFIED
}

func (x *ControlPayload) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ControlPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlPayload) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ControlPayload) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

var File_internal_transport_transportpb_frame_proto protoreflect.FileDescriptor

const file_internal_transport_transportpb_frame_proto_rawDesc = "" +
	"\n" +
	"*internal/transport/transportpb/frame.proto\x12\x18voicestream.transport.v1\"u\n" +
	"\vTextPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final\x12<\n" +
	"\x06source\x18\x03 \x01(\x0e2$.voicestream.transport.v1.TextSourceR\x06source\"\xb3\x01\n" +
	"\x0eControlPayload\x129\n" +
	"\x04kind\x18\x01 \x01(\x0e2%.voicestream.transport.v1.ControlKindR\x04kind\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x04R\alastSeq*j\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FRAME_TYPE_AUDIO\x10\x01\x12\x13\n" +
	"\x0fFRAME_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12FRAME_TYPE_CONTROL\x10\x03*\\\n" +
	"\n" +
	"TextSource\x12\x1b\n" +
	"\x17TEXT_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TEXT_SOURCE_TRANSCRIPT\x10\x01\x12\x15\n" +
	"\x11TEXT_SOURCE_TOKEN\x10\x02*\x8d\x01\n" +
	"\vControlKind\x12\x1c\n" +
	"\x18CONTROL_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTROL_KIND_START\x10\x01\x12\x15\n" +
	"\x11CONTROL_KIND_STOP\x10\x02\x12\x19\n" +
	"\x15CONTROL_KIND_BARGE_IN\x10\x03\x12\x16\n" +
	"\x12CONTROL_KIND_ERROR\x10\x04B8Z6voicestream/internal/transport/transportpb;transportpbb\x06proto3"

var (
	file_internal_transport_transportpb_frame_proto_rawDescOnce sync.Once
	file_internal_transport_transportpb_frame_proto_rawDescData []byte
)

func file_internal_transport_transportpb_frame_proto_rawDescGZIP() []byte {
	file_internal_transport_transportpb_frame_proto_rawDescOnce.Do(func() {
		file_internal_transport_transportpb_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_transportpb_frame_proto_rawDesc), len(file_internal_transport_transportpb_frame_proto_rawDesc)))
	})
	return file_internal_transport_transportpb_frame_proto_rawDescData
}

var file_internal_transport_transportpb_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_transport_transportpb_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_transportpb_frame_proto_goTypes = []any{
	(FrameType)(0),         // 0: voicestream.transport.v1.FrameType
	(TextSource)(0),        // 1: voicestream.transport.v1.TextSource
	(ControlKind)(0),       // 2: voicestream.transport.v1.ControlKind
	(*TextPayload)(nil),    // 3: voicestream.transport.v1.TextPayload
	(*ControlPayload)(nil), // 4: voicestream.transport.v1.ControlPayload
}
var file_internal_transport_transportpb_frame_proto_depIdxs = []int32{
	1, // 0: voicestream.transport.v1.TextPayload.source:type_name -> voicestream.transport.v1.TextSource
	2, // 1: voicestream.transport.v1.ControlPayload.kind:type_name -> voicestream.transport.v1.ControlKind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_transport_transportpb_frame_proto_init() }
func file_internal_transport_transportpb_frame_proto_init() {
	if File_internal_transport_transportpb_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_transportpb_frame_proto_rawDesc), len(file_internal_transport_transportpb_frame_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_transport_transportpb_frame_proto_goTypes,
		DependencyIndexes: file_internal_transport_transportpb_frame_proto_depIdxs,
		EnumInfos:         file_internal_transport_transportpb_frame_proto_enumTypes,
		MessageInfos:      file_internal_transport_transportpb_frame_proto_msgTypes,
	}.Build()
	File_internal_transport_transportpb_frame_proto = out.File
	file_internal_transport_transportpb_frame_proto_goTypes = nil
	file_internal_transport_transportpb_frame_proto_depIdxs = nil
}
